<?php
/**
 * Manage News in the database.
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

interface NewsManager
{
	public function get(int $id) : News;
	public function getList(int $numberOfNews = null, int $startPosition = null) : array;
    public function save(News $news) : bool;
	public function delete(News  $news) : bool;
}
