<?php
/**
 * Manage News in the database.
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

interface NewsManager
{

	public function add(News  $news): bool;
	public function get(int $id) : News;
	public function getList(int $numberOfNews, int $startPosition) : array;
	public function update(News  $news) : bool;
	public function delete(News  $news) : bool;
    public function save(News $news) : bool;

}
