<?php
namespace Entity;

use OCFram\Entity;
use \DateTime;

/**
 * A news have an ID for the database storage, an author, a title, a content, a creation date and an edition date.
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class News extends Entity
{

    ////////////////
    // Properties //
    ////////////////


	/**
	 * Author of the news.
	 * @var String
	 * @access protected
	 */
	protected  $author = null;

	/**
	 * Title of the news.
	 * @var String
	 * @access protected
	 */
	protected  $title = null;

	/**
	 * Content of the news.
	 * @var String
	 * @access protected
	 */
	protected  $content = null;

	/**
	 * Date indicating when the news has been added.
	 * @var DateTime
	 * @access protected
	 */
	protected  $dateAdded = null;

	/**
	 * Date indicating when the news has been edited for the last time.
	 * @var DateTime
	 * @access protected
	 */
	protected  $dateEdited = null;

    /////////////
    // Methods //
    /////////////


    /**
     * Return true if the news has an author, a title and a content. Else, retourn false.
     * @return bool
     */
    public function isValid() : bool
    {
        return !(empty($this->author) or empty($this->title) or empty($this->content));
    }

    /////////////
    // Setters //
    /////////////

    /**
	 * Set the author.
	 * @access public
	 * @param String $author Author to set to the news.
	 */
    public function setAuthor(String $author)
    {
        $this->author = $author;
    }


    /**
    * Set the title.
    * @access public
    * @param String $title Title to set to the news.
    */

    public function setTitle(String $title)
    {
        $this->title = $title;
    }


    /**
    * Set the content.
    * @access public
    * @param String $content Content to set to the news.
    */

    public function setContent(String $content)
    {
        $this->content = $content;
    }


    /**
    * Set the creation date.
    * @access public
    * @param DateTime $dateAdded Creation date to set to the news.
    */

    public function setDateAdded(DateTime $dateAdded)
    {
        $this->dateAdded = $dateAdded;
    }


    /**
    * Set the last edition date.
    * @access public
    * @param DateTime $dateEdited Edition date to set to the news.
    */

    public function setDateEdited(DateTime $dateEdited = null)
    {
        $this->dateEdited = $dateEdited;
    }

    /////////////
    // Getters //
    /////////////


    /**
    * Return the author.
    * @access public
    * @return ?String
    */
	public function getAuthor() : ?String
    {
        return $this->author;
	}


	/**
	 * Return the title.
	 * @access public
	 * @return ?String
	 */

	public function getTitle() : ?String
    {
        return $this->title;
	}


	/**
	 * Return the content.
	 * @access public
	 * @return ?String
	 */

	public function getContent() : ?String
    {
        return $this->content;
	}


	/**
	 * Return the creation date.
	 * @access public
	 * @return ?DateTime
	 */

	public function getDateAdded() : ?DateTime
    {
        return $this->dateAdded;
	}


	/**
	 * Return the last edition date.
	 * @access public
	 * @return ?DateTime
	 */

	public function getDateEdited() : ?DateTime
    {
        return $this->dateEdited;
	}

}
